---
# - hosts: localhost
#   gather_facts: True
#   # vars_files: ./deploy-vars.yml
#   tasks:
#     - set_fact: localhost_user="{{ lookup('env','USER') | default('ERROR', True) }}"

#     - name: Install Git
#       package:
#         name: git
#         state: latest
#       become: true

#     - name: Git Clone yay role
#       git:
#         repo: https://github.com/stiliajohny/ansible-role-yay.git
#         dest: "./roles/ansible-role-yay"
#       delegate_to: 127.0.0.1
#       become: true
#       become_user: "{{ localhost_user }}"
#       ignore_errors: true

#     - name: Git Clone xorg role
#       git:
#         repo: https://github.com/stiliajohny/ansible-role-xorg.git
#         dest: "./roles/ansible-role-xorg"
#       delegate_to: 127.0.0.1
#       become: true
#       become_user: "{{ localhost_user }}"
#       ignore_errors: true

#     - name: Git Clone VNC role
#       git:
#         repo: https://github.com/stiliajohny/ansible-role-vnc.git
#         dest: "./roles/ansible-role-vnc"
#       delegate_to: 127.0.0.1
#       become: true
#       become_user: "{{ localhost_user }}"
#       ignore_errors: true

#     - name: Git Clone I3WM role
#       git:
#         repo: https://github.com/stiliajohny/ansible-role-i3.git
#         dest: "./roles/ansible-role-i3"
#       delegate_to: 127.0.0.1
#       become: true
#       become_user: "{{ localhost_user }}"
#       ignore_errors: true

#     - name: Git Clone ASDF role
#       git:
#         repo: https://github.com/stiliajohny/ansible-role-asdf.git
#         dest: "./roles/ansible-role-asdf"
#       delegate_to: 127.0.0.1
#       become: true
#       become_user: "{{ localhost_user }}"
#       ignore_errors: true

#     - name: Git Clone server_banners_prompts role
#       git:
#         repo: https://github.com/stiliajohny/ansible-role-server-banners-prompts.git
#         dest: "./roles/ansible-role-server-banners-prompts"
#       delegate_to: 127.0.0.1
#       become: true
#       become_user: "{{ localhost_user }}"
#       ignore_errors: true

#     - name: Git Clone ansible-role-code-server role
#       git:
#         repo: https://github.com/stiliajohny/ansible-role-code-server.git
#         dest: "./roles/ansible-role-code-server"
#       delegate_to: 127.0.0.1
#       become: true
#       become_user: "{{ localhost_user }}"
#       ignore_errors: true

#     - name: Git Clone ansible-role-python role
#       git:
#         repo: https://github.com/stiliajohny/ansible-role-python.git
#         dest: "./roles/ansible-role-python"
#       delegate_to: 127.0.0.1
#       become: true
#       become_user: "{{ localhost_user }}"
#       ignore_errors: true

#     - name: Git Clone ansible-role-patching role
#       git:
#         repo: https://github.com/stiliajohny/ansible-role-patching.git
#         dest: "./roles/ansible-role-patching"
#       delegate_to: 127.0.0.1
#       become: true
#       become_user: "{{ localhost_user }}"
#       ignore_errors: true

#     - name: Git Clone ansible-role-apps role
#       git:
#         repo: https://github.com/stiliajohny/ansible-role-app.git
#         dest: "./roles/ansible-role-apps"
#       delegate_to: 127.0.0.1
#       become: true
#       become_user: "{{ localhost_user }}"
#       ignore_errors: true

#     - name: Git Clone ansible-role-docker role
#       git:
#         repo: https://github.com/stiliajohny/ansible-role-docker.git
#         dest: "./roles/ansible-role-docker"
#       delegate_to: 127.0.0.1
#       become: true
#       become_user: "{{ localhost_user }}"
#       ignore_errors: true

#     - name: Git Clone ansible-role-zsh role
#       git:
#         repo: https://github.com/stiliajohny/ansible-role-zsh.git
#         dest: "./roles/ansible-role-zsh"
#       delegate_to: 127.0.0.1
#       become: true
#       become_user: "{{ localhost_user }}"
#       ignore_errors: true

#     - name: Git Clone ansible-role-visual-studio-code role
#       git:
#         repo: https://github.com/gantsign/ansible-role-visual-studio-code.git
#         dest: "./roles/ansible-role-visual-studio-code"
#       delegate_to: 127.0.0.1
#       become: true
#       become_user: "{{ localhost_user }}"
#       ignore_errors: true

- hosts: localhost
  tasks:
    - docker_container:
        name: dev-box
        image: docker-dev-box-ubuntu:xfce-18.04-dev
        published_ports:
          - 6080:6080
          - 5900:5900
        command: sleep 1d

- name: Run pre-req software on devbox
  hosts: dev-box
  tasks:
    - name: Run the equivalent of "apt-get update" as a separate step
      apt:
        update_cache: yes
    - name: Run the equivalent of "apt-get update" as a separate step
      apt:
        name: "sudo"
        state: present
        update_cache: yes

- name: Run Roles on devbox
  hosts: dev-box
  become: true
  become_user: root
  roles:
    # - { role: ansible-role-patching, tags: ["ansible-role-patching"] } # mostly leave enabled as it does a cache update
    # - { role: ansible-role-xorg, tags: ["ansible-role-xorg"] }
    # - { role: ansible-role-i3, tags: ["ansible-role-i3"] }
    - { role: ansible-role-apps, tags: ["ansible-role-apps"] }
    - { role: ansible-role-python, tags: ["ansible-role-python"] }
    # - { role: ansible-role-docker, tags: ["ansible-role-docker"] }
    - { role: ansible-role-asdf, tags: ["ansible-role-asdf"] }
    - { role: ansible-role-zsh, tags: ["ansible-role-zsh"] }
    - { role: ansible-role-visual-studio-code, tags: ["ansible-role-visual-studio-code"] }
# - {
#     role: ansible-role-server-banners-prompts,
#     tags: ["ansible-role-server-banners-prompts"],
#   }
# - { role: ansible-role-code-server, tags: ["ansible-role-code-server"] }
# - { role: ansible-role-vnc, tags: ["ansible-role-vnc"] }
# - { role: ansible-role-yay, tags: ["ansible-role-yay"] }
# ignore_errors: true
# - name: Preparing Docker Image
#   hosts: 127.0.0.1
#   tasks:
#     - name: Commit the docker container
#       shell: "docker commit dev-box"
#       register: docker_commit_sha

#     - name: Docker Image SHA Signature
#       debug:
#         msg: "{{ docker_commit_sha.stdout.split(':')[1] }}"

#     - name: Tag the docker container
#       shell: "docker tag {{ docker_commit_sha.stdout.split(':')[1] }} debian-dev-box"

# - hosts: localhost
#   tasks:
#     - name: Destroy the container
#       docker_container:
#         name: dev-box
#         state: absent
